// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { MdDialog } from '@angular/material';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { UsersService } from './../services/users.service';

// Models imports
import { Users } from '../users.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

@Component({
  selector: 'app-users-list',
  templateUrl: './users-list.component.html',
  styleUrls: ['./users-list.component.css']
})
export class UsersListComponent implements OnInit, OnChanges {

  private listOfUserss: Users[];
  private listId = 'USERS_COMPONENT_LIST';

  private title = 'List of Userss';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _usersService: UsersService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService,
    public dialog: MdDialog) { }

  ngOnInit() {
    // On init get all Userss
    this.getAllUserss();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Users list
    EmitterService.get(this.listId).subscribe((data: Users[]) => this.getAllUserss());
  }

  ngOnChanges() { }

  /**
   * Get all Users using the service UsersService
   */
  getAllUserss = (): void => {
    this._usersService.getAll().subscribe(
      (data: Users[]) => {
        this.listOfUserss = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editUsers = (id): void => {
    // Navigate to users form component
    this.goToUsersForm(id);
  }

  deleteUsers = (id): void => {
    // Call delete service
    this._usersService.delete(id).subscribe(
      result => {
        // Notify Users list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The users entry with the id='${id}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });
  }

  goToUsersForm(id) {
    this._router.navigate(['./users-form', id]);
  }

  deleteConfirmation = (id) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `users: ${id}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteUsers(id);
      }
    });
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfUserss.length, page);

    // get current page of items
    this.pagedItems = this.listOfUserss.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
