// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { MdDialog } from '@angular/material';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { ProviderxjobService } from './../services/providerxjob.service';

// Models imports
import { Providerxjob } from '../providerxjob.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

@Component({
  selector: 'app-providerxjob-list',
  templateUrl: './providerxjob-list.component.html',
  styleUrls: ['./providerxjob-list.component.css']
})
export class ProviderxjobListComponent implements OnInit, OnChanges {

  private listOfProviderxjobs: Providerxjob[];
  private listId = 'PROVIDERXJOB_COMPONENT_LIST';

  private title = 'List of Providerxjobs';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _providerxjobService: ProviderxjobService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService,
    public dialog: MdDialog) { }

  ngOnInit() {
    // On init get all Providerxjobs
    this.getAllProviderxjobs();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Providerxjob list
    EmitterService.get(this.listId).subscribe((data: Providerxjob[]) => this.getAllProviderxjobs());
  }

  ngOnChanges() { }

  /**
   * Get all Providerxjob using the service ProviderxjobService
   */
  getAllProviderxjobs = (): void => {
    this._providerxjobService.getAll().subscribe(
      (data: Providerxjob[]) => {
        this.listOfProviderxjobs = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editProviderxjob = (id): void => {
    // Navigate to providerxjob form component
    this.goToProviderxjobForm(id);
  }

  deleteProviderxjob = (id): void => {
    // Call delete service
    this._providerxjobService.delete(id).subscribe(
      result => {
        // Notify Providerxjob list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The providerxjob entry with the id='${id}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });
  }

  goToProviderxjobForm(id) {
    this._router.navigate(['./providerxjob-form', id]);
  }

  deleteConfirmation = (id) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `providerxjob: ${id}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteProviderxjob(id);
      }
    });
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfProviderxjobs.length, page);

    // get current page of items
    this.pagedItems = this.listOfProviderxjobs.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
