// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

import { GenericService } from './../../../services/generic.service';
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { Jobs } from '../jobs.model';
import { Configuration } from '../../../app.configuration';

@Injectable()
export class JobsService extends GenericService<Jobs>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(_http: Http, _configuration: Configuration) {
        super(_http, _configuration, 'jobs/');
    }

}
