// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MdDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

// Models and services imports
import { Sequelizemeta } from './../sequelizemeta.model';
import { SequelizemetaService } from './../services/sequelizemeta.service';
import * as _ from 'underscore';

@Component({
  selector: 'app-sequelizemeta-form',
  templateUrl: './sequelizemeta-form.component.html',
  styleUrls: ['./sequelizemeta-form.component.css']
})
export class SequelizemetaFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  private title = 'Sequelizemeta Form';
  private sequelizemeta: Sequelizemeta;
  private form: FormGroup;
  private ids;

  constructor(
    private _sequelizemetaService: SequelizemetaService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MdDialog) { }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = (sequelizemeta?: Sequelizemeta) => {
    return {
      name: [{
        value: (sequelizemeta ? sequelizemeta.name : ''),
        disabled: true
      }]
    };
  }


  load = () => {
    this._sequelizemetaService.getSingle(this.ids).subscribe(
      (sequelizemeta: Sequelizemeta) => {
        this.sequelizemeta = {
          name: sequelizemeta.name
		};
        this.form = this._formBuilder.group(this.getNewForm(this.sequelizemeta));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a sequelizemeta, we are adding a sequelizemeta
    if (!this.sequelizemeta) {
      this.add();
    } else { // If we didn't get a sequelizemeta, we are adding a sequelizemeta
      this.update();
    }
  }

  add = () => {
    this._sequelizemetaService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Sequelizemeta added successfuly');
        this._router.navigate(['./sequelizemeta-form', this.form.value.name]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._sequelizemetaService.update(<Sequelizemeta>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'Sequelizemeta edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.sequelizemeta.name) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `sequelizemeta: ${this.sequelizemeta.name}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.sequelizemeta.name);
        }
      });
    }
  }

  deleteBadge = (name): void => {
    // Call delete service
    this._sequelizemetaService.delete(name).subscribe(
      result => {
        this._router.navigate(['./sequelizemeta-list']);

        this._notificationService.success(
          'Deleted',
          `The sequelizemeta entry with the id(s)='${name}' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
