/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:08:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa.mapping;

/**
 * Mapper provider 
 *
 * @author Telosys
 * 
 */
public interface JpaMapperProvider {

	/**
	 * Returns the current mapper instance
	 * @return
	 */
	public <JPA,POJO> JpaMapper<JPA,POJO> getMapper(Class<JPA> jpaClass, Class<POJO> pojoClass) ;
}
