/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:21:09 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa.mapping;

// Choose you mapper implementation here
// import org.demo.persistence.impl.jpa.mapping.modelmapper.JpaMapperProviderImpl;
import org.demo.persistence.impl.jpa.mapping.manual.JpaMapperProviderImpl;

/**
 * Use this class to choose your prefered mapping implementation 
 *
 * @author Telosys
 *
 */
public class JpaMapping {

	/**
	 * Current mapper provider
	 */
	private static JpaMapperProvider mapperProvider = new JpaMapperProviderImpl() ;
	
	/**
	 * Set the current mapper provider
	 * @param provider
	 */
	protected static void setMapperProvider(JpaMapperProvider provider) {
		mapperProvider = provider ;
	}
	
	/**
	 * Returns the current mapper provider
	 * @return
	 */
	public static JpaMapperProvider getMapperProvider() {
		return mapperProvider;
	}
}
