/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:08:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa.mapping;

/**
 * Interface for mapping between JPA class and POJO class.
 *
 * @author Telosys
 */
public interface JpaMapper<JPA,POJO> {

	/**
	 * Mapping from 'JPA Record' to 'POJO Record'
	 * @param entity the mapping input 
	 */
	public POJO mapEntityToRecord ( JPA entity) ;

	/**
	 * Mapping from 'POJO Record' to 'JPA Record' 
	 * @param record the mapping input 
	 * @return
	 */
	public JPA mapRecordToEntity(POJO record) ;

}