// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

export interface Providerxjob {
	id: number; // Wrapper Type : Number
	providerid: number; // Wrapper Type : Number
	jobid: number; // Wrapper Type : Number
}
