// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MdDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

// Models and services imports
import { Users } from './../users.model';
import { UsersService } from './../services/users.service';
import * as _ from 'underscore';

@Component({
  selector: 'app-users-form',
  templateUrl: './users-form.component.html',
  styleUrls: ['./users-form.component.css']
})
export class UsersFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  private title = 'Users Form';
  private users: Users;
  private form: FormGroup;
  private ids;

  constructor(
    private _usersService: UsersService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MdDialog) { }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = (users?: Users) => {
    return {
      id: [
          (users ? users.id : ''),
          Validators.required
      ],
      name: [
        (users ? users.name : '')
      ],
      email: [
        (users ? users.email : ''),
        Validators.required
      ],
      password: [
        (users ? users.password : ''),
        Validators.required
      ],
      createdat: [
        (users ? users.createdat : ''),
        Validators.required
      ],
      updatedat: [
        (users ? users.updatedat : ''),
        Validators.required
      ]
    };
  }


  load = () => {
    this._usersService.getSingle(this.ids).subscribe(
      (users: Users) => {
        this.users = {
          id: users.id,
          name: users.name,
          email: users.email,
          password: users.password,
          createdat: users.createdat,
          updatedat: users.updatedat
		};
        this.form = this._formBuilder.group(this.getNewForm(this.users));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a users, we are adding a users
    if (!this.users) {
      this.add();
    } else { // If we didn't get a users, we are adding a users
      this.update();
    }
  }

  add = () => {
    this._usersService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Users added successfuly');
        this._router.navigate(['./users-form', this.form.value.id]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._usersService.update(<Users>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'Users edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.users.id) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `users: ${this.users.id}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.users.id);
        }
      });
    }
  }

  deleteBadge = (id): void => {
    // Call delete service
    this._usersService.delete(id).subscribe(
      result => {
        this._router.navigate(['./users-list']);

        this._notificationService.success(
          'Deleted',
          `The users entry with the id(s)='${id}' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
