// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

import { Injectable } from '@angular/core';

@Injectable()
export class Configuration {
    public server = 'http://localhost:3000';
    public apiUrl = '/api/v1/';
    public serverWithApiUrl = this.server + this.apiUrl;
}
