// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

import { NotificationService } from './services/notification.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  title: String = 'Home';

  public navigation = [
		{ title: 'Jobs', routerLink: 'jobs-list' },
		{ title: 'Providers', routerLink: 'providers-list' },
		{ title: 'Providerxjob', routerLink: 'providerxjob-list' },
		{ title: 'Sequelizemeta', routerLink: 'sequelizemeta-list' },
		{ title: 'Users', routerLink: 'users-list' }
  ];

  public optionsForNotifications = {
    position: ['bottom', 'left'],
    timeOut: 5000,
    lastOnBottom: true,
    showProgressBar: false,
    pauseOnHover: false,
    clickToClose: true,
    preventDuplicates: true
  };

  constructor(
    private _notificationService: NotificationService) { }

  ngOnInit() {
    this._notificationService.init();
  }
}
