// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

import { Router, RouterModule } from '@angular/router';
import { NotFoundComponent } from './not-found/not-found.component';
import { AboutComponent } from './about/about.component';
import { HomeListComponent } from './home-list/home-list.component';

// Jobs
import { JobsListComponent } from './entities/jobs/jobs-list/jobs-list.component';
import { JobsFormComponent } from './entities/jobs/jobs-form/jobs-form.component';

// Providers
import { ProvidersListComponent } from './entities/providers/providers-list/providers-list.component';
import { ProvidersFormComponent } from './entities/providers/providers-form/providers-form.component';

// Providerxjob
import { ProviderxjobListComponent } from './entities/providerxjob/providerxjob-list/providerxjob-list.component';
import { ProviderxjobFormComponent } from './entities/providerxjob/providerxjob-form/providerxjob-form.component';

// Sequelizemeta
import { SequelizemetaListComponent } from './entities/sequelizemeta/sequelizemeta-list/sequelizemeta-list.component';
import { SequelizemetaFormComponent } from './entities/sequelizemeta/sequelizemeta-form/sequelizemeta-form.component';

// Users
import { UsersListComponent } from './entities/users/users-list/users-list.component';
import { UsersFormComponent } from './entities/users/users-form/users-form.component';

export const routing = RouterModule.forRoot([
    { path: '', component: HomeListComponent },
    { path: 'jobs-list', component: JobsListComponent },
    { path: 'jobs-form/:id', component: JobsFormComponent },
    { path: 'jobs-form', component: JobsFormComponent },
    { path: 'providers-list', component: ProvidersListComponent },
    { path: 'providers-form/:id', component: ProvidersFormComponent },
    { path: 'providers-form', component: ProvidersFormComponent },
    { path: 'providerxjob-list', component: ProviderxjobListComponent },
    { path: 'providerxjob-form/:id', component: ProviderxjobFormComponent },
    { path: 'providerxjob-form', component: ProviderxjobFormComponent },
    { path: 'sequelizemeta-list', component: SequelizemetaListComponent },
    { path: 'sequelizemeta-form/:id', component: SequelizemetaFormComponent },
    { path: 'sequelizemeta-form', component: SequelizemetaFormComponent },
    { path: 'users-list', component: UsersListComponent },
    { path: 'users-form/:id', component: UsersFormComponent },
    { path: 'users-form', component: UsersFormComponent },
    { path: 'about', component: AboutComponent },
    { path: '**', component: NotFoundComponent }
]);