// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';

// Routing
import { routing } from './app.routing';

// Jobs Components
import { JobsListComponent } from './entities/jobs/jobs-list/jobs-list.component';
import { JobsFormComponent } from './entities/jobs/jobs-form/jobs-form.component';

// Providers Components
import { ProvidersListComponent } from './entities/providers/providers-list/providers-list.component';
import { ProvidersFormComponent } from './entities/providers/providers-form/providers-form.component';

// Providerxjob Components
import { ProviderxjobListComponent } from './entities/providerxjob/providerxjob-list/providerxjob-list.component';
import { ProviderxjobFormComponent } from './entities/providerxjob/providerxjob-form/providerxjob-form.component';

// Sequelizemeta Components
import { SequelizemetaListComponent } from './entities/sequelizemeta/sequelizemeta-list/sequelizemeta-list.component';
import { SequelizemetaFormComponent } from './entities/sequelizemeta/sequelizemeta-form/sequelizemeta-form.component';

// Users Components
import { UsersListComponent } from './entities/users/users-list/users-list.component';
import { UsersFormComponent } from './entities/users/users-form/users-form.component';

// Other Components
import { NotFoundComponent } from './not-found/not-found.component';
import { AboutComponent } from './about/about.component';
import { DeleteDialogComponent } from './delete-dialog/delete-dialog.component';
import { HomeListComponent } from './home-list/home-list.component';

// Modules
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { SimpleNotificationsModule } from 'angular2-notifications';
import { MaterialModule, MdNativeDateModule } from '@angular/material';

// Services
import { Configuration } from './app.configuration';
import { JobsService } from './entities/jobs/services/jobs.service';
import { ProvidersService } from './entities/providers/services/providers.service';
import { ProviderxjobService } from './entities/providerxjob/services/providerxjob.service';
import { SequelizemetaService } from './entities/sequelizemeta/services/sequelizemeta.service';
import { UsersService } from './entities/users/services/users.service';
import { EmitterService } from './services/emitter.service';
import { NotificationService } from './services/notification.service';
import { PagerService } from './services/pager.service';

@NgModule({
  declarations: [
    AppComponent,
    JobsListComponent,
    JobsFormComponent,
    ProvidersListComponent,
    ProvidersFormComponent,
    ProviderxjobListComponent,
    ProviderxjobFormComponent,
    SequelizemetaListComponent,
    SequelizemetaFormComponent,
    UsersListComponent,
    UsersFormComponent,
    NotFoundComponent,
    AboutComponent,
    DeleteDialogComponent,
    HomeListComponent
],
  entryComponents: [
    DeleteDialogComponent
],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    routing,
    BrowserAnimationsModule,
    MaterialModule,
    MdNativeDateModule,
    SimpleNotificationsModule.forRoot()
],
  providers: [
    JobsService,
    ProvidersService,
    ProviderxjobService,
    SequelizemetaService,
    UsersService,
    Configuration,
    EmitterService,
    NotificationService,
    PagerService
],
  bootstrap: [AppComponent]
})
export class AppModule { }
