/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:21:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa.mapping;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.demo.data.record.JobsRecord;
import org.demo.persistence.impl.jpa.record.JobsJpaRecord ;

/**
 * Generic tests for Jobs mapping
 *
 */
public abstract class JobsMappingGenericTest {

	protected void setMapperProvider(JpaMapperProvider provider) {
		JpaMapping.setMapperProvider(provider);
		System.out.println("Mapper provider set to : " + provider.getClass().getCanonicalName() );
	}
	
	protected void processAllTest() {
		testPojoMapping();
		testEntityMapping();
	}
	
	private JobsJpaRecord buildJpaRecord() {
		JobsJpaRecord entity = new JobsJpaRecord();
		entity.setId(Integer.valueOf(100)); 
		entity.setName("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); 
		entity.setImage("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); 
		return entity ;
	}
	
	private JobsRecord buildRecord() {
		JobsRecord pojo = new JobsRecord();
		pojo.setId(Integer.valueOf(100)); 
		pojo.setName("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); 
		pojo.setImage("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); 
		return pojo ;
	}

	private void checkValues(JobsRecord r1, JobsRecord r2) {
		assertTrue(r1 != r2); // different instances
		assertEquals(r1.getId(), r2.getId());
		assertEquals(r1.getName(), r2.getName());
		assertEquals(r1.getImage(), r2.getImage());
	}

	private void checkValues(JobsJpaRecord r1, JobsJpaRecord r2) {
		assertTrue(r1 != r2); // different instances
		assertEquals(r1.getId(), r2.getId());
		assertEquals(r1.getName(), r2.getName());
		assertEquals(r1.getImage(), r2.getImage());
	}
	
	protected void testPojoMapping() {
		System.out.println("Test POJO mapping" );
    	JpaMapper<JobsJpaRecord,JobsRecord> mapper = JpaMapping.getMapperProvider().getMapper(JobsJpaRecord.class, JobsRecord.class);
    	JobsRecord pojo1 = buildRecord();
    	JobsJpaRecord entity = mapper.mapRecordToEntity(pojo1);
    	JobsRecord pojo2 = mapper.mapEntityToRecord(entity);
    	checkValues(pojo1, pojo2);
    	// Test null 
    	assertNull(mapper.mapRecordToEntity(null));
	}
	
	protected void testEntityMapping() {
		System.out.println("Test ENTITY mapping" );
    	JpaMapper<JobsJpaRecord,JobsRecord> mapper = JpaMapping.getMapperProvider().getMapper(JobsJpaRecord.class, JobsRecord.class);
		JobsJpaRecord entity1 = buildJpaRecord();
		JobsRecord pojo = mapper.mapEntityToRecord(entity1);
		JobsJpaRecord entity2 = mapper.mapRecordToEntity(pojo);
    	checkValues(entity1, entity2);
    	// Test null 
    	assertNull(mapper.mapEntityToRecord(null));
	}
	
}
