// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

export interface Providers {
	id: number; // Wrapper Type : Number
	userid: number; // Wrapper Type : Number
	phone: number; // Wrapper Type : Number
	description: string; // Wrapper Type : String
	address: string; // Wrapper Type : String
	createdat: Date; // Wrapper Type : Date
	updatedat: Date; // Wrapper Type : Date
}
