// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home-list',
  templateUrl: './home-list.component.html',
  styleUrls: ['./home-list.component.css']
})
export class HomeListComponent implements OnInit {

  public navigation = [
		{ title: 'Jobs', routerLink: 'jobs-list' },
		{ title: 'Providers', routerLink: 'providers-list' },
		{ title: 'Providerxjob', routerLink: 'providerxjob-list' },
		{ title: 'Sequelizemeta', routerLink: 'sequelizemeta-list' },
		{ title: 'Users', routerLink: 'users-list' }
  ];

  constructor() { }

  ngOnInit() {
  }

}
