/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:21:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa.mapping.manual;

import org.demo.data.record.JobsRecord;
import org.demo.persistence.impl.jpa.mapping.JpaMapper;
import org.demo.persistence.impl.jpa.record.JobsJpaRecord;

/**
 * Manual mapping for "Jobs" 
 *
 * @author Telosys
 *
 */
public class JobsManualMapper implements JpaMapper<JobsJpaRecord, JobsRecord> {

	@Override
	public JobsRecord mapEntityToRecord(JobsJpaRecord entity) {
		if ( entity == null ) return null ;
		JobsRecord pojo = new JobsRecord();
		pojo.setId(entity.getId()); 
		pojo.setName(entity.getName()); 
		pojo.setImage(entity.getImage()); 
		return pojo;
	}

	@Override
	public JobsJpaRecord mapRecordToEntity(JobsRecord pojo) {
		if ( pojo == null ) return null ;
		JobsJpaRecord entity = new JobsJpaRecord();
		entity.setId(pojo.getId()); 
		entity.setName(pojo.getName()); 
		entity.setImage(pojo.getImage()); 
		return entity;
	}

}
