/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:08:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa.mapping.manual;

import org.demo.data.record.ProviderxjobRecord;
import org.demo.persistence.impl.jpa.mapping.JpaMapper;
import org.demo.persistence.impl.jpa.record.ProviderxjobJpaRecord;

/**
 * Manual mapping for "Providerxjob" 
 *
 * @author Telosys
 *
 */
public class ProviderxjobManualMapper implements JpaMapper<ProviderxjobJpaRecord, ProviderxjobRecord> {

	@Override
	public ProviderxjobRecord mapEntityToRecord(ProviderxjobJpaRecord entity) {
		if ( entity == null ) return null ;
		ProviderxjobRecord pojo = new ProviderxjobRecord();
		pojo.setId(entity.getId()); 
		pojo.setProviderid(entity.getProviderid()); 
		pojo.setJobid(entity.getJobid()); 
		return pojo;
	}

	@Override
	public ProviderxjobJpaRecord mapRecordToEntity(ProviderxjobRecord pojo) {
		if ( pojo == null ) return null ;
		ProviderxjobJpaRecord entity = new ProviderxjobJpaRecord();
		entity.setId(pojo.getId()); 
		entity.setProviderid(pojo.getProviderid()); 
		entity.setJobid(pojo.getJobid()); 
		return entity;
	}

}
