/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:08:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa.mapping.manual;

import org.demo.data.record.UsersRecord;
import org.demo.persistence.impl.jpa.mapping.JpaMapper;
import org.demo.persistence.impl.jpa.record.UsersJpaRecord;

/**
 * Manual mapping for "Users" 
 *
 * @author Telosys
 *
 */
public class UsersManualMapper implements JpaMapper<UsersJpaRecord, UsersRecord> {

	@Override
	public UsersRecord mapEntityToRecord(UsersJpaRecord entity) {
		if ( entity == null ) return null ;
		UsersRecord pojo = new UsersRecord();
		pojo.setId(entity.getId()); 
		pojo.setName(entity.getName()); 
		pojo.setEmail(entity.getEmail()); 
		pojo.setPassword(entity.getPassword()); 
		pojo.setCreatedat(entity.getCreatedat()); 
		pojo.setUpdatedat(entity.getUpdatedat()); 
		return pojo;
	}

	@Override
	public UsersJpaRecord mapRecordToEntity(UsersRecord pojo) {
		if ( pojo == null ) return null ;
		UsersJpaRecord entity = new UsersJpaRecord();
		entity.setId(pojo.getId()); 
		entity.setName(pojo.getName()); 
		entity.setEmail(pojo.getEmail()); 
		entity.setPassword(pojo.getPassword()); 
		entity.setCreatedat(pojo.getCreatedat()); 
		entity.setUpdatedat(pojo.getUpdatedat()); 
		return entity;
	}

}
