// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

export interface Jobs {
	id: number; // Wrapper Type : Number
	name: string; // Wrapper Type : String
	image: string; // Wrapper Type : String
}
