// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

import { Component, Inject } from '@angular/core';
import { MdDialogRef, MD_DIALOG_DATA } from '@angular/material';

@Component({
  selector: 'app-delete-dialog',
  template: `
    <h2 md-dialog-title>Delete {{ data }}</h2>
    <md-dialog-content>Are you sure?</md-dialog-content>
    <md-dialog-actions>
        <button md-button md-dialog-close>No</button>
        <button md-button [md-dialog-close]="true">Yes</button>
    </md-dialog-actions>
  `
})
export class DeleteDialogComponent {

  constructor(
      public dialogRef: MdDialogRef<DeleteDialogComponent>, 
      @Inject(MD_DIALOG_DATA) public data: any) { }
}