/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:04:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */

package org.demo.persistence.commons;

/**
 * The pattern defined here is used by the Persistence Service Provider <br>
 * to build the service implementation class name <br>
 * 
 * @author Telosys
 *
 */
public class PersistenceJpaServicePattern {

	public final static String  PATTERN = "%s.impl.jpa.%sJpa" ;
	
}
