// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  title: String = 'About';

  constructor() { }

  ngOnInit() {
  }

}