// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

export interface Users {
	id: number; // Wrapper Type : Number
	name: string; // Wrapper Type : String
	email: string; // Wrapper Type : String
	password: string; // Wrapper Type : String
	createdat: Date; // Wrapper Type : Date
	updatedat: Date; // Wrapper Type : Date
}
