/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:04:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.ProvidersPersistence ;
import org.demo.persistence.ProvidersPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Providers persistence service
 * 
 * @author Telosys Tools
 *
 */
public class ProvidersPersistenceJpaTest extends ProvidersPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	ProvidersPersistence persistenceService = new ProvidersPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
