/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:04:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.ProviderxjobPersistence ;
import org.demo.persistence.ProviderxjobPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Providerxjob persistence service
 * 
 * @author Telosys Tools
 *
 */
public class ProviderxjobPersistenceJpaTest extends ProviderxjobPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	ProviderxjobPersistence persistenceService = new ProviderxjobPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
