/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:04:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.SequelizemetaPersistence ;
import org.demo.persistence.SequelizemetaPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Sequelizemeta persistence service
 * 
 * @author Telosys Tools
 *
 */
public class SequelizemetaPersistenceJpaTest extends SequelizemetaPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	SequelizemetaPersistence persistenceService = new SequelizemetaPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
