/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:04:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.jpa;

import org.demo.persistence.UsersPersistence ;
import org.demo.persistence.UsersPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Users persistence service
 * 
 * @author Telosys Tools
 *
 */
public class UsersPersistenceJpaTest extends UsersPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	UsersPersistence persistenceService = new UsersPersistenceJpa();


    	testPersistenceService(persistenceService);
	}	
}
