// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { MdDialog } from '@angular/material';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { ProvidersService } from './../services/providers.service';

// Models imports
import { Providers } from '../providers.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

@Component({
  selector: 'app-providers-list',
  templateUrl: './providers-list.component.html',
  styleUrls: ['./providers-list.component.css']
})
export class ProvidersListComponent implements OnInit, OnChanges {

  private listOfProviderss: Providers[];
  private listId = 'PROVIDERS_COMPONENT_LIST';

  private title = 'List of Providerss';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _providersService: ProvidersService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService,
    public dialog: MdDialog) { }

  ngOnInit() {
    // On init get all Providerss
    this.getAllProviderss();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Providers list
    EmitterService.get(this.listId).subscribe((data: Providers[]) => this.getAllProviderss());
  }

  ngOnChanges() { }

  /**
   * Get all Providers using the service ProvidersService
   */
  getAllProviderss = (): void => {
    this._providersService.getAll().subscribe(
      (data: Providers[]) => {
        this.listOfProviderss = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editProviders = (id): void => {
    // Navigate to providers form component
    this.goToProvidersForm(id);
  }

  deleteProviders = (id): void => {
    // Call delete service
    this._providersService.delete(id).subscribe(
      result => {
        // Notify Providers list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The providers entry with the id='${id}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });
  }

  goToProvidersForm(id) {
    this._router.navigate(['./providers-form', id]);
  }

  deleteConfirmation = (id) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `providers: ${id}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteProviders(id);
      }
    });
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfProviderss.length, page);

    // get current page of items
    this.pagedItems = this.listOfProviderss.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
