// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { MdDialog } from '@angular/material';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { JobsService } from './../services/jobs.service';

// Models imports
import { Jobs } from '../jobs.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

@Component({
  selector: 'app-jobs-list',
  templateUrl: './jobs-list.component.html',
  styleUrls: ['./jobs-list.component.css']
})
export class JobsListComponent implements OnInit, OnChanges {

  private listOfJobss: Jobs[];
  private listId = 'JOBS_COMPONENT_LIST';

  private title = 'List of Jobss';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _jobsService: JobsService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService,
    public dialog: MdDialog) { }

  ngOnInit() {
    // On init get all Jobss
    this.getAllJobss();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Jobs list
    EmitterService.get(this.listId).subscribe((data: Jobs[]) => this.getAllJobss());
  }

  ngOnChanges() { }

  /**
   * Get all Jobs using the service JobsService
   */
  getAllJobss = (): void => {
    this._jobsService.getAll().subscribe(
      (data: Jobs[]) => {
        this.listOfJobss = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editJobs = (id): void => {
    // Navigate to jobs form component
    this.goToJobsForm(id);
  }

  deleteJobs = (id): void => {
    // Call delete service
    this._jobsService.delete(id).subscribe(
      result => {
        // Notify Jobs list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The jobs entry with the id='${id}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });
  }

  goToJobsForm(id) {
    this._router.navigate(['./jobs-form', id]);
  }

  deleteConfirmation = (id) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `jobs: ${id}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteJobs(id);
      }
    });
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfJobss.length, page);

    // get current page of items
    this.pagedItems = this.listOfJobss.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
