// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-06-09 ( Time 12:14:13 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { MdDialog } from '@angular/material';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { SequelizemetaService } from './../services/sequelizemeta.service';

// Models imports
import { Sequelizemeta } from '../sequelizemeta.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

@Component({
  selector: 'app-sequelizemeta-list',
  templateUrl: './sequelizemeta-list.component.html',
  styleUrls: ['./sequelizemeta-list.component.css']
})
export class SequelizemetaListComponent implements OnInit, OnChanges {

  private listOfSequelizemetas: Sequelizemeta[];
  private listId = 'SEQUELIZEMETA_COMPONENT_LIST';

  private title = 'List of Sequelizemetas';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _sequelizemetaService: SequelizemetaService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService,
    public dialog: MdDialog) { }

  ngOnInit() {
    // On init get all Sequelizemetas
    this.getAllSequelizemetas();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Sequelizemeta list
    EmitterService.get(this.listId).subscribe((data: Sequelizemeta[]) => this.getAllSequelizemetas());
  }

  ngOnChanges() { }

  /**
   * Get all Sequelizemeta using the service SequelizemetaService
   */
  getAllSequelizemetas = (): void => {
    this._sequelizemetaService.getAll().subscribe(
      (data: Sequelizemeta[]) => {
        this.listOfSequelizemetas = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editSequelizemeta = (name): void => {
    // Navigate to sequelizemeta form component
    this.goToSequelizemetaForm(name);
  }

  deleteSequelizemeta = (name): void => {
    // Call delete service
    this._sequelizemetaService.delete(name).subscribe(
      result => {
        // Notify Sequelizemeta list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The sequelizemeta entry with the id='${name}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });
  }

  goToSequelizemetaForm(name) {
    this._router.navigate(['./sequelizemeta-form', name]);
  }

  deleteConfirmation = (name) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `sequelizemeta: ${name}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteSequelizemeta(name);
      }
    });
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfSequelizemetas.length, page);

    // get current page of items
    this.pagedItems = this.listOfSequelizemetas.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
