/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:04:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */

package org.demo.persistence.impl.jpa;


import java.util.List;

import javax.inject.Named;

import org.demo.data.record.JobsRecord; // "Neutral Record" class 
import org.demo.persistence.JobsPersistence; // Persistence service interface
import org.demo.persistence.impl.jpa.commons.GenericJpaService;
import org.demo.persistence.impl.jpa.mapping.JpaMapper;
import org.demo.persistence.impl.jpa.mapping.JpaMapping;

import org.demo.persistence.impl.jpa.record.JobsJpaRecord; // "JPA Record" class (with JPA mapping) 

/**
 * Jobs persistence service - JPA implementation 
 * 
 * @author Telosys 
 *
 */
@Named("JobsPersistence")
public class JobsPersistenceJpa extends GenericJpaService<JobsJpaRecord, Integer> implements JobsPersistence {

	private final JpaMapper<JobsJpaRecord,JobsRecord> mapper = JpaMapping.getMapperProvider().getMapper(JobsJpaRecord.class,JobsRecord.class);

	/**
	 * Constructor
	 */
	public JobsPersistenceJpa() {
		super(JobsJpaRecord.class);
	}

	@Override
	public JobsRecord findById( Integer id ) {
		JobsJpaRecord entity = super.find( id );
		return mapper.mapEntityToRecord(entity);	
	}

	@Override
	public List<JobsRecord> findAll() {
		List<JobsJpaRecord> entities = super.loadAll() ;
		List<JobsRecord> records = new java.util.LinkedList<JobsRecord>();
		for ( JobsJpaRecord entity : entities ) {
			records.add( mapper.mapEntityToRecord(entity) ) ;
		}
		return records ;
	}

	@Override
	public JobsRecord create(JobsRecord record) {
		JobsJpaRecord entity = mapper.mapRecordToEntity(record);
		super.persist(entity);
		return record ;
	}
	
	@Override
	public boolean update(JobsRecord record) {
		Integer pk = record.getId() ;
		if ( super.find( pk ) != null ) {
			// Exists => 'merge' 
			JobsJpaRecord entity = mapper.mapRecordToEntity(record);
			super.merge(entity);
			return true ;
		}
		else {
			return false;
		}
	}

	@Override
	public JobsRecord save(JobsRecord record) {
		JobsJpaRecord entity = mapper.mapRecordToEntity(record);
		super.merge(entity);
		return record ;
	}

	@Override
	public boolean deleteById( Integer id ) {
		return super.remove( id );
	}

	@Override
	public boolean delete(JobsRecord record) {
		if ( record != null ) {
			return super.remove( record.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countAll") ) ;
		return count.longValue();
	}

	public long countById(Integer id) {
		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countById"), id ) ;
		return count.longValue();
	}
	
	@Override
	public boolean exists(Integer id) {
		long count = countById(id) ;
		return count > 0 ;
	}


	@Override
	public boolean exists(JobsRecord record) {
		if ( record != null ) {
			return exists( record.getId() );
		}
		return false ;
	}

	@SuppressWarnings("unchecked")
	public List<JobsJpaRecord> queryExample() {
		List<?> list = super.execNamedQuery(buildQueryName("theNamedQueryToBeUsed")) ;
		return (List<JobsJpaRecord>) list ;
	}

}
