/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:04:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */

package org.demo.persistence.impl.jpa;


import java.util.List;

import javax.inject.Named;

import org.demo.data.record.ProviderxjobRecord; // "Neutral Record" class 
import org.demo.persistence.ProviderxjobPersistence; // Persistence service interface
import org.demo.persistence.impl.jpa.commons.GenericJpaService;
import org.demo.persistence.impl.jpa.mapping.JpaMapper;
import org.demo.persistence.impl.jpa.mapping.JpaMapping;

import org.demo.persistence.impl.jpa.record.ProviderxjobJpaRecord; // "JPA Record" class (with JPA mapping) 

/**
 * Providerxjob persistence service - JPA implementation 
 * 
 * @author Telosys 
 *
 */
@Named("ProviderxjobPersistence")
public class ProviderxjobPersistenceJpa extends GenericJpaService<ProviderxjobJpaRecord, Integer> implements ProviderxjobPersistence {

	private final JpaMapper<ProviderxjobJpaRecord,ProviderxjobRecord> mapper = JpaMapping.getMapperProvider().getMapper(ProviderxjobJpaRecord.class,ProviderxjobRecord.class);

	/**
	 * Constructor
	 */
	public ProviderxjobPersistenceJpa() {
		super(ProviderxjobJpaRecord.class);
	}

	@Override
	public ProviderxjobRecord findById( Integer id ) {
		ProviderxjobJpaRecord entity = super.find( id );
		return mapper.mapEntityToRecord(entity);	
	}

	@Override
	public List<ProviderxjobRecord> findAll() {
		List<ProviderxjobJpaRecord> entities = super.loadAll() ;
		List<ProviderxjobRecord> records = new java.util.LinkedList<ProviderxjobRecord>();
		for ( ProviderxjobJpaRecord entity : entities ) {
			records.add( mapper.mapEntityToRecord(entity) ) ;
		}
		return records ;
	}

	@Override
	public ProviderxjobRecord create(ProviderxjobRecord record) {
		ProviderxjobJpaRecord entity = mapper.mapRecordToEntity(record);
		super.persist(entity);
		return record ;
	}
	
	@Override
	public boolean update(ProviderxjobRecord record) {
		Integer pk = record.getId() ;
		if ( super.find( pk ) != null ) {
			// Exists => 'merge' 
			ProviderxjobJpaRecord entity = mapper.mapRecordToEntity(record);
			super.merge(entity);
			return true ;
		}
		else {
			return false;
		}
	}

	@Override
	public ProviderxjobRecord save(ProviderxjobRecord record) {
		ProviderxjobJpaRecord entity = mapper.mapRecordToEntity(record);
		super.merge(entity);
		return record ;
	}

	@Override
	public boolean deleteById( Integer id ) {
		return super.remove( id );
	}

	@Override
	public boolean delete(ProviderxjobRecord record) {
		if ( record != null ) {
			return super.remove( record.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countAll") ) ;
		return count.longValue();
	}

	public long countById(Integer id) {
		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countById"), id ) ;
		return count.longValue();
	}
	
	@Override
	public boolean exists(Integer id) {
		long count = countById(id) ;
		return count > 0 ;
	}


	@Override
	public boolean exists(ProviderxjobRecord record) {
		if ( record != null ) {
			return exists( record.getId() );
		}
		return false ;
	}

	@SuppressWarnings("unchecked")
	public List<ProviderxjobJpaRecord> queryExample() {
		List<?> list = super.execNamedQuery(buildQueryName("theNamedQueryToBeUsed")) ;
		return (List<ProviderxjobJpaRecord>) list ;
	}

}
