/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 11:53:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.springdatajpa.service;

import java.util.List;
import java.util.Optional;

import org.demo.data.record.JobsRecord;
import org.demo.persistence.JobsPersistence;
import org.demo.persistence.impl.jpa.record.JobsJpaRecord;
import org.demo.persistence.impl.springdatajpa.repository.JobsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.demo.persistence.impl.jpa.mapping.JpaMapper;
import org.demo.persistence.impl.jpa.mapping.JpaMapping;

/**
 * Spring persistence service for "Jobs" <br>
 * @author Telosys (http://www.telosys.org/) version 3.1.2
 */
@Service
@Transactional
public class JobsPersistenceService implements JobsPersistence {

	@Autowired
	private JobsRepository jobsRepository;
	//@Autowired
	//private JobsMapper jobsMapper;
	private final JpaMapper<JobsJpaRecord,JobsRecord> mapper = JpaMapping.getMapperProvider().getMapper(JobsJpaRecord.class,JobsRecord.class);


	@Override
	public JobsRecord findById(Integer id) {

		Optional<JobsJpaRecord> optionalEntity = jobsRepository.findById(id);
		if ( optionalEntity.isPresent() ) {
			return mapper.mapEntityToRecord(optionalEntity.get());
		}
		return null ;

	}

	@Override
	public List<JobsRecord> findAll() {
		//return mapper.mapEntityToRecord(jobsRepository.findAll());

		List<JobsJpaRecord> entities = jobsRepository.findAll() ;
		List<JobsRecord> records = new java.util.LinkedList<JobsRecord>();
		for ( JobsJpaRecord entity : entities ) {
			records.add( mapper.mapEntityToRecord(entity) ) ;
		}
		return records ;

	}

	@Override
	public long countAll() {
		return jobsRepository.count();
	}

	@Override
	public JobsRecord save(JobsRecord record) {
//		return mapper.map(jobsRepository.save(mapper.map(record)));
		JobsJpaRecord saved = jobsRepository.save( mapper.mapRecordToEntity(record) );
		return mapper.mapEntityToRecord(saved);

	}

	@Override
	public boolean update(JobsRecord record) {

		if ( exists(record) ) {
			jobsRepository.save(mapper.mapRecordToEntity(record));
			return true;
		}
		return false;
	}

	@Override
	public JobsRecord create(JobsRecord record) {
		JobsJpaRecord saved = jobsRepository.save( mapper.mapRecordToEntity(record) );
		return mapper.mapEntityToRecord(saved);

	}

	@Override
	public boolean deleteById(Integer id) {
		final Optional<JobsJpaRecord> optinalEntity = jobsRepository.findById(id);
		if( ! optinalEntity.isPresent() ) {
			return false;
		}

		else {
			jobsRepository.delete(optinalEntity.get());
			return true;
		}
	}

	@Override
	public boolean delete(JobsRecord record) {
		if(record == null) {
			return false;
		}
		return deleteById( record.getId() );

	}

	@Override
	public boolean exists(Integer id) {
		return jobsRepository.findById(id).isPresent();
	}

	@Override
	public boolean exists(JobsRecord record) {
		return record == null ? false : jobsRepository.findById(record.getId()).isPresent();
	}

}
