/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 11:53:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.springdatajpa.service;

import java.util.List;
import java.util.Optional;

import org.demo.data.record.ProvidersRecord;
import org.demo.persistence.ProvidersPersistence;
import org.demo.persistence.impl.jpa.record.ProvidersJpaRecord;
import org.demo.persistence.impl.springdatajpa.repository.ProvidersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.demo.persistence.impl.jpa.mapping.JpaMapper;
import org.demo.persistence.impl.jpa.mapping.JpaMapping;

/**
 * Spring persistence service for "Providers" <br>
 * @author Telosys (http://www.telosys.org/) version 3.1.2
 */
@Service
@Transactional
public class ProvidersPersistenceService implements ProvidersPersistence {

	@Autowired
	private ProvidersRepository providersRepository;
	//@Autowired
	//private ProvidersMapper providersMapper;
	private final JpaMapper<ProvidersJpaRecord,ProvidersRecord> mapper = JpaMapping.getMapperProvider().getMapper(ProvidersJpaRecord.class,ProvidersRecord.class);


	@Override
	public ProvidersRecord findById(Integer id) {

		Optional<ProvidersJpaRecord> optionalEntity = providersRepository.findById(id);
		if ( optionalEntity.isPresent() ) {
			return mapper.mapEntityToRecord(optionalEntity.get());
		}
		return null ;

	}

	@Override
	public List<ProvidersRecord> findAll() {
		//return mapper.mapEntityToRecord(providersRepository.findAll());

		List<ProvidersJpaRecord> entities = providersRepository.findAll() ;
		List<ProvidersRecord> records = new java.util.LinkedList<ProvidersRecord>();
		for ( ProvidersJpaRecord entity : entities ) {
			records.add( mapper.mapEntityToRecord(entity) ) ;
		}
		return records ;

	}

	@Override
	public long countAll() {
		return providersRepository.count();
	}

	@Override
	public ProvidersRecord save(ProvidersRecord record) {
//		return mapper.map(providersRepository.save(mapper.map(record)));
		ProvidersJpaRecord saved = providersRepository.save( mapper.mapRecordToEntity(record) );
		return mapper.mapEntityToRecord(saved);

	}

	@Override
	public boolean update(ProvidersRecord record) {

		if ( exists(record) ) {
			providersRepository.save(mapper.mapRecordToEntity(record));
			return true;
		}
		return false;
	}

	@Override
	public ProvidersRecord create(ProvidersRecord record) {
		ProvidersJpaRecord saved = providersRepository.save( mapper.mapRecordToEntity(record) );
		return mapper.mapEntityToRecord(saved);

	}

	@Override
	public boolean deleteById(Integer id) {
		final Optional<ProvidersJpaRecord> optinalEntity = providersRepository.findById(id);
		if( ! optinalEntity.isPresent() ) {
			return false;
		}

		else {
			providersRepository.delete(optinalEntity.get());
			return true;
		}
	}

	@Override
	public boolean delete(ProvidersRecord record) {
		if(record == null) {
			return false;
		}
		return deleteById( record.getId() );

	}

	@Override
	public boolean exists(Integer id) {
		return providersRepository.findById(id).isPresent();
	}

	@Override
	public boolean exists(ProvidersRecord record) {
		return record == null ? false : providersRepository.findById(record.getId()).isPresent();
	}

}
