/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 11:53:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.springdatajpa.service;

import java.util.List;
import java.util.Optional;

import org.demo.data.record.UsersRecord;
import org.demo.persistence.UsersPersistence;
import org.demo.persistence.impl.jpa.record.UsersJpaRecord;
import org.demo.persistence.impl.springdatajpa.repository.UsersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.demo.persistence.impl.jpa.mapping.JpaMapper;
import org.demo.persistence.impl.jpa.mapping.JpaMapping;

/**
 * Spring persistence service for "Users" <br>
 * @author Telosys (http://www.telosys.org/) version 3.1.2
 */
@Service
@Transactional
public class UsersPersistenceService implements UsersPersistence {

	@Autowired
	private UsersRepository usersRepository;
	//@Autowired
	//private UsersMapper usersMapper;
	private final JpaMapper<UsersJpaRecord,UsersRecord> mapper = JpaMapping.getMapperProvider().getMapper(UsersJpaRecord.class,UsersRecord.class);


	@Override
	public UsersRecord findById(Integer id) {

		Optional<UsersJpaRecord> optionalEntity = usersRepository.findById(id);
		if ( optionalEntity.isPresent() ) {
			return mapper.mapEntityToRecord(optionalEntity.get());
		}
		return null ;

	}

	@Override
	public List<UsersRecord> findAll() {
		//return mapper.mapEntityToRecord(usersRepository.findAll());

		List<UsersJpaRecord> entities = usersRepository.findAll() ;
		List<UsersRecord> records = new java.util.LinkedList<UsersRecord>();
		for ( UsersJpaRecord entity : entities ) {
			records.add( mapper.mapEntityToRecord(entity) ) ;
		}
		return records ;

	}

	@Override
	public long countAll() {
		return usersRepository.count();
	}

	@Override
	public UsersRecord save(UsersRecord record) {
//		return mapper.map(usersRepository.save(mapper.map(record)));
		UsersJpaRecord saved = usersRepository.save( mapper.mapRecordToEntity(record) );
		return mapper.mapEntityToRecord(saved);

	}

	@Override
	public boolean update(UsersRecord record) {

		if ( exists(record) ) {
			usersRepository.save(mapper.mapRecordToEntity(record));
			return true;
		}
		return false;
	}

	@Override
	public UsersRecord create(UsersRecord record) {
		UsersJpaRecord saved = usersRepository.save( mapper.mapRecordToEntity(record) );
		return mapper.mapEntityToRecord(saved);

	}

	@Override
	public boolean deleteById(Integer id) {
		final Optional<UsersJpaRecord> optinalEntity = usersRepository.findById(id);
		if( ! optinalEntity.isPresent() ) {
			return false;
		}

		else {
			usersRepository.delete(optinalEntity.get());
			return true;
		}
	}

	@Override
	public boolean delete(UsersRecord record) {
		if(record == null) {
			return false;
		}
		return deleteById( record.getId() );

	}

	@Override
	public boolean exists(Integer id) {
		return usersRepository.findById(id).isPresent();
	}

	@Override
	public boolean exists(UsersRecord record) {
		return record == null ? false : usersRepository.findById(record.getId()).isPresent();
	}

}
