/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:21:09 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */

package org.demo.persistence.impl.jpa.mapping.manual;

import static org.junit.Assert.assertEquals;

import org.demo.data.record.UsersRecord;
import org.demo.persistence.impl.jpa.mapping.UsersMappingGenericTest;
import org.demo.persistence.impl.jpa.mapping.JpaMapper;
import org.junit.Test;

/**
 * Mapping tests for Users with 'manual mapping'
 * 
 * @author Telosys
 *
 */
public class UsersManualMappingTest extends UsersMappingGenericTest {

	@Test
	public void testGetMapperInstance() {

		JpaMapperProviderImpl provider = new JpaMapperProviderImpl();
		JpaMapper<?,?> mapper = provider.getMapperInstance(UsersRecord.class);
		assertEquals("UsersManualMapper", mapper.getClass().getSimpleName());
	}	

	@Test
	public void testMapping() {

		setMapperProvider(new JpaMapperProviderImpl()) ;
		processAllTest();
	}	
}
