/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:21:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */

package org.demo.persistence.impl.jpa.record;

import java.io.Serializable;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for "Providers" entity stored in table "Providers" <br>
 * This class is a "record entity" without JPA links  <br>
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Providers", catalog="agser" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ProvidersJpaRecord.countAll",  query="SELECT COUNT(x) FROM ProvidersJpaRecord x" ),
  @NamedQuery ( name="ProvidersJpaRecord.countById", query="SELECT COUNT(x) FROM ProvidersJpaRecord x WHERE x.id = ?1 " )
} )
public class ProvidersJpaRecord implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="id", nullable=false)
    private Integer    id           ; 

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="userId", nullable=false)
    private Integer    userid       ; // Foreign Key 

    @Column(name="phone", nullable=false)
    private Integer    phone        ; 

    @Column(name="description", nullable=false, length=255)
    private String     description  ; 

    @Column(name="address", nullable=false, length=255)
    private String     address      ; 

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdAt", nullable=false)
    private Date       createdat    ; 

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedAt", nullable=false)
    private Date       updatedat    ; 


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ProvidersJpaRecord() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : userId ( INT ) 
    public void setUserid( Integer userid ) {
        this.userid = userid;
    }
    public Integer getUserid() {
        return this.userid;
    }

    //--- DATABASE MAPPING : phone ( INT ) 
    public void setPhone( Integer phone ) {
        this.phone = phone;
    }
    public Integer getPhone() {
        return this.phone;
    }

    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : address ( VARCHAR ) 
    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    //--- DATABASE MAPPING : createdAt ( DATETIME ) 
    public void setCreatedat( Date createdat ) {
        this.createdat = createdat;
    }
    public Date getCreatedat() {
        return this.createdat;
    }

    //--- DATABASE MAPPING : updatedAt ( DATETIME ) 
    public void setUpdatedat( Date updatedat ) {
        this.updatedat = updatedat;
    }
    public Date getUpdatedat() {
        return this.updatedat;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(userid);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(createdat);
        sb.append("|");
        sb.append(updatedat);
        return sb.toString(); 
    } 

}
