/*
 * Created on 2020-06-09 ( Date ISO 2020-06-09 - Time 12:08:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */

package org.demo.persistence.impl.jpa.record;

import java.io.Serializable;


import javax.persistence.*;

/**
 * Persistent class for "Sequelizemeta" entity stored in table "SequelizeMeta" <br>
 * This class is a "record entity" without JPA links  <br>
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="SequelizeMeta", catalog="agser" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SequelizemetaJpaRecord.countAll",  query="SELECT COUNT(x) FROM SequelizemetaJpaRecord x" ),
  @NamedQuery ( name="SequelizemetaJpaRecord.countById", query="SELECT COUNT(x) FROM SequelizemetaJpaRecord x WHERE x.name = ?1 " )
} )
public class SequelizemetaJpaRecord implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="name", nullable=false, length=255)
    private String     name         ; 

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SequelizemetaJpaRecord() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(name);
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
